# Generated by Django 6.0.3 on 2026-03-05 04:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('course_url', models.URLField()),
                ('skill_level', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=20)),
                ('certification', models.BooleanField()),
                ('language', models.CharField(max_length=50)),
                ('learning_mode', models.CharField(max_length=20)),
                ('duration', models.CharField(max_length=50)),
                ('rating', models.FloatField()),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='api.platform')),
            ],
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_level', models.CharField(max_length=20)),
                ('plan', models.CharField(max_length=20)),
                ('certification_needed', models.BooleanField()),
                ('language', models.CharField(max_length=50)),
                ('learning_mode', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
