# Generated by Django 6.0.3 on 2026-03-05 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_platform_course_userpreference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='certification',
        ),
        migrations.RemoveField(
            model_name='course',
            name='price',
        ),
        migrations.AddField(
            model_name='course',
            name='certificate_available',
            field=models.BooleanField(default=False, help_text='Does this course offer a certificate?'),
        ),
        migrations.AddField(
            model_name='course',
            name='is_certificate_free',
            field=models.BooleanField(default=False, help_text='True if certificate is free, False if paid'),
        ),
        migrations.AddField(
            model_name='course',
            name='is_course_free',
            field=models.BooleanField(default=True, help_text='True if course content is free, False if paid'),
        ),
        migrations.AlterField(
            model_name='course',
            name='learning_mode',
            field=models.CharField(choices=[('Video', 'Video'), ('Text', 'Text'), ('Mixed', 'Mixed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='skill_level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='learning_mode',
            field=models.CharField(choices=[('Video', 'Video'), ('Text', 'Text'), ('Mixed', 'Mixed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='plan',
            field=models.CharField(choices=[('Free', 'Free'), ('Paid', 'Paid')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='skill_level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], max_length=20),
        ),
    ]
