# Generated by Django 6.0.3 on 2026-03-19 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_userpreference_course_alter_userpreference_language'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='course',
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='course_name',
            field=models.CharField(default='default', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='certificate_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_certificate_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_course_free',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='language',
            field=models.CharField(choices=[('english', 'English'), ('hindi', 'Hindi')], max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='learning_mode',
            field=models.CharField(choices=[('video', 'Video'), ('text', 'Text'), ('mixed', 'Mixed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='skill_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='language',
            field=models.CharField(choices=[('english', 'English'), ('hindi', 'Hindi')], max_length=50),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='learning_mode',
            field=models.CharField(choices=[('video', 'Video'), ('text', 'Text')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='plan',
            field=models.CharField(choices=[('free', 'Free'), ('paid', 'Paid')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='skill_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20),
        ),
    ]
