# Generated by Django 6.0.3 on 2026-03-19 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_course_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='is_certificate_free',
        ),
    ]
