# Generated by Django 6.0.3 on 2026-03-28 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_course_popularity_score_course_views_count_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-rating']},
        ),
        migrations.AlterModelOptions(
            name='userhistory',
            options={'ordering': ['-searched_at']},
        ),
        migrations.AlterField(
            model_name='course',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
