# Generated by Django 6.0.3 on 2026-03-29 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_review_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='course',
        ),
    ]
