# Generated by Django 6.0.3 on 2026-03-29 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_searchhistory_delete_userhistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchhistory',
            old_name='query',
            new_name='course_name',
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='platform',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
