# Generated by Django 6.0.3 on 2026-03-29 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_rename_query_searchhistory_course_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchhistory',
            name='certification_needed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='language',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='learning_mode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='plan',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='skill_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
