# Generated by Django 6.0.3 on 2026-03-29 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_searchhistory_certification_needed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchhistory',
            name='platform',
        ),
    ]
