# Generated by Django 6.0.3 on 2026-03-30 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_remove_searchhistory_platform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='created_at',
            new_name='saved_at',
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.course'),
        ),
    ]
