# Generated by Django 6.0.3 on 2026-03-30 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_rename_created_at_favorite_saved_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='saved_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='favorite',
            name='platform',
            field=models.CharField(default='YouTube', max_length=100),
        ),
        migrations.AddField(
            model_name='favorite',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='favorite',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.course'),
        ),
    ]
