# Generated by Django 6.0.3 on 2026-03-05 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_course_certification_remove_course_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
