# Generated by Django 6.0.3 on 2026-03-05 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_platform_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.course'),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='language',
            field=models.CharField(choices=[('English', 'English'), ('Hindi', 'Hindi')], max_length=50),
        ),
    ]
