# Generated by Django 6.0.3 on 2026-03-19 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_delete_djangomigrations_remove_userpreference_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
