# Generated by Django 6.0.3 on 2026-03-28 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_course_duration_favorite_review_userhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_url',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='userhistory',
            name='course_name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='certification_needed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='course_name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='language',
            field=models.CharField(blank=True, choices=[('english', 'English'), ('hindi', 'Hindi')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='learning_mode',
            field=models.CharField(blank=True, choices=[('video', 'Video'), ('text', 'Text')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='plan',
            field=models.CharField(blank=True, choices=[('free', 'Free'), ('paid', 'Paid')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='skill_level',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20, null=True),
        ),
    ]
