# Generated by Django 6.0.3 on 2026-03-28 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_course_updated_at_review_helpful_count_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-popularity_score', '-created_at']},
        ),
        migrations.RemoveField(
            model_name='course',
            name='rating',
        ),
    ]
